[package]
name = "flexism"
version = "0.1.0"
edition = "2021"

[dependencies]


[workspace]
# resolver = "2"
members = [ 
  "crates/flexism-host",
  "crates/flexism-plugin",
  "crates/flexism-plugin/examples/test-plugin"
]

